const fs=require('fs');const {JSDOM}=require('jsdom');
const html=fs.readFileSync('/home/claude/6flt-photoshoot-map/c/index.html','utf8').replace(/<script src=[^>]*><\/script>/g,'').replace(/<link href=[^>]*>/g,'');
let fails=0;const check=(l,c)=>{console.log((c?'OK   ':'FAIL ')+l);if(!c)fails++;};
const brief={revealed:true,reveal_at:null,confirmed_at:null,html:'<div class="bf-row" data-layout="1"><div class="bf-slot"><div class="bf-blk" data-type="text">x</div></div></div>',data:{title:'T',start:'2026-10-15T12:00:00Z',end:'2026-10-15T14:00:00Z',tone:'tu',handle:'_6flt_'},title:'Séance test',gallery_url:null};
const dom=new JSDOM(html,{url:'https://x.github.io/6flt-photoshoot-map/c/?b=TEST6fltClients29',runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){
  Object.defineProperty(w.navigator,'userAgent',{value:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1'});
  w.matchMedia=()=>({matches:false});w.Notification=function(){};w.Notification.permission='default';
  w.supabase={createClient:()=>({rpc:(n)=>Promise.resolve({data:n.indexOf('shared_brief')>-1?brief:true,error:null})})};
}});
const w=dom.window, d=w.document, disp=el=>w.getComputedStyle(el).display;
setTimeout(()=>{
  const m=d.getElementById('modal-add');
  check('au chargement : panneau Ajouter masqué a l\'ecran', disp(m)==='none');
  check('seance ouverte : vue detail affichee', disp(d.getElementById('cv-root'))==='block');
  const bar=d.querySelector('#cv-root .cv-bar');
  check('barre du bas (Je confirme, PDF) presente et visible', !!bar && disp(bar)!=='none' && /Je confirme/.test(bar.textContent));
  const ib=d.querySelector('#cv-install .js-inst-open');
  check('carte : bouton Installer l\'app present et visible', !!ib && disp(ib)!=='none');
  d.getElementById('btn-add').click();
  check('bouton + : panneau affiche', disp(m)==='flex');
  d.getElementById('add-go').click();
  check('valider vide : message d\'erreur', d.getElementById('add-err').textContent.length>0);
  const inp=d.getElementById('add-input'); inp.value='1'; inp.dispatchEvent(new w.Event('input'));
  check('taper efface le message d\'erreur', d.getElementById('add-err').textContent==='');
  d.getElementById('add-cancel').click();
  check('Annuler : panneau masque', disp(m)==='none');
  d.getElementById('btn-add').click(); m.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
  check('toucher le fond : panneau masque', disp(m)==='none');
  console.log(fails?fails+' ECHEC(S)':'TOUS LES TESTS PASSENT');process.exit(fails?1:0);
},200);
