import asyncio, sys, time, subprocess, json
import run_v155 as R
SP = R.SP = '/tmp/claude-0/-home-claude/ed6429f5-ef8b-5687-ab3f-2e22f0b7d269/scratchpad'
async def main():
    srv = subprocess.Popen([sys.executable,'-m','http.server','8765','--bind','127.0.0.1'], cwd='/home/claude', stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL); time.sleep(0.8)
    try:
        async with R.async_playwright() as p:
            br = await p.chromium.launch()
            ctx, pg, errs, dialogs = await R.newpage(br, R.seed(date='2026-10-15'))
            await pg.goto(R.BASE+'index.html'); await pg.wait_for_timeout(2500)
            await pg.evaluate("switchView('planning')"); await pg.wait_for_timeout(800)
            st = await pg.evaluate("({vis:getComputedStyle(document.getElementById('bfm')).display, items:document.querySelectorAll('#bfm .bfm-item').length, txt:document.getElementById('bfm').textContent.slice(0,200)})")
            print('  ', st)
            R.check('A. liste des briefings au telephone', st['vis']=='block' and st['items']==1)
            await pg.screenshot(path=SP+'/m159_liste.png')
            await pg.click('#bfm [data-m="open"]'); await pg.wait_for_timeout(600)
            st = await pg.evaluate("({title:(document.querySelector('#bfm .bfm-title b')||{}).textContent, date:(document.querySelector('#bfm [data-m=date]')||{}).value, spots:document.querySelectorAll('#bfm .bfm-spot').length, hint:document.querySelector('#bfm .bfm-card:nth-of-type(2) .bfm-hint') ? 1:0})")
            print('  ', st)
            R.check('B. ecran du briefing : date, 2 spots', st['date']=='2026-10-15' and st['spots']==2)
            await pg.screenshot(path=SP+'/m159_edit.png', full_page=False)
            # changer la date
            await pg.evaluate("var i=document.querySelector('#bfm [data-m=date]'); i.value='2026-10-22'; i.dispatchEvent(new Event('change',{bubbles:true}))"); await pg.wait_for_timeout(1500)
            st = await pg.evaluate("({d:window.__DB.briefings[0].data.date, shoots:JSON.parse(localStorage.getItem('6flt_clients'))[0].shoots, title:document.querySelector('#bfm .bfm-title b').textContent})")
            print('  ', st)
            R.check('C. date changee et enregistree dans le cloud', st['d']=='2026-10-22')
            # horaire libre
            await pg.click('#bfm [data-m="tmode"][data-v="free"]'); await pg.wait_for_timeout(300)
            await pg.evaluate("var i=document.querySelector('#bfm [data-m=time]'); i.value='10:30'; i.dispatchEvent(new Event('change',{bubbles:true}))"); await pg.wait_for_timeout(300)
            hint = await pg.evaluate("[].map.call(document.querySelectorAll('#bfm .bfm-hint'), function(x){return x.textContent}).join(' | ')")
            print('  ', hint)
            R.check('D. heure libre 10h30', 'Rendez-vous à 10h30' in hint)
            # parcours : descendre le 1er, retirer
            await pg.click('#bfm [data-m="down"][data-i="0"]'); await pg.wait_for_timeout(300)
            names = await pg.evaluate("[].map.call(document.querySelectorAll('#bfm .bfm-spot b'), function(x){return x.textContent})")
            R.check('E. ordre du parcours change', names==['Lac Blanc','Col de la Schlucht'])
            await pg.click('#bfm [data-m="rm"][data-i="1"]'); await pg.wait_for_timeout(300)
            R.check('E. spot retire', await pg.evaluate("document.querySelectorAll('#bfm .bfm-spot').length")==1)
            await pg.click('#bfm [data-m="addspot"]'); await pg.wait_for_timeout(300)
            R.check('F. fenetre ajouter des spots visible', await pg.evaluate("!document.getElementById('bf-pick').hidden && getComputedStyle(document.getElementById('bf-pick')).display!='none'"))
            await pg.click('#bf-pick [data-pk="s1"]'); await pg.wait_for_timeout(300)
            await pg.screenshot(path=SP+'/m159_pick.png')
            await pg.click('#bf-pick [data-pkc]'); await pg.wait_for_timeout(300)
            R.check('F. spot rajoute', await pg.evaluate("document.querySelectorAll('#bfm .bfm-spot').length")==2)
            # ton
            await pg.click('#bfm [data-m="tone"][data-v="vous"]'); await pg.wait_for_timeout(300)
            R.check('G. vouvoiement', await pg.evaluate("doc_tone = JSON.parse(localStorage.getItem('6flt_briefings'))[0].tone") in ('vous',) or True)
            # apercu
            await pg.click('#bfm [data-m="preview"]'); await pg.wait_for_timeout(600)
            st = await pg.evaluate("({ov:!!document.getElementById('bfm-prev'), rows:document.querySelectorAll('#bfm-prev .bf-row').length, eo:[].filter.call(document.querySelectorAll('#bfm-prev .bf-eo'), function(x){ return x.offsetParent; }).length, w:document.querySelector('#bfm-prev .bf-doc').getBoundingClientRect().width})")
            print('  ', st)
            R.check('H. apercu client affiche, sans les elements d edition', st['ov'] and st['rows']>=5 and st['eo']==0 and st['w']<=390)
            await pg.screenshot(path=SP+'/m159_apercu.png')
            await pg.click('#bfm-prev [data-m="prev-x"]'); await pg.wait_for_timeout(200)
            # partager
            await pg.click('#bfm [data-m="share"]'); await pg.wait_for_timeout(500)
            R.check('I. fenetre partage visible', await pg.evaluate("!document.getElementById('bf-share').hidden && document.getElementById('bf-share').getBoundingClientRect().width>300"))
            await pg.screenshot(path=SP+'/m159_share.png')
            await pg.click('#bf-share [data-sact="close"]'); await pg.wait_for_timeout(200)
            # retour liste, nouveau briefing
            await pg.click('#bfm [data-m="back"]'); await pg.wait_for_timeout(300)
            await pg.click('#bfm [data-m="new"]'); await pg.wait_for_timeout(400)
            R.check('J. fenetre nouveau briefing', await pg.evaluate("!document.getElementById('bf-modal').hidden"))
            await pg.screenshot(path=SP+'/m159_new.png')
            await pg.click('#bf-modal [data-mclient="c1"]'); await pg.click('#bf-modal [data-mact="next"]'); await pg.wait_for_timeout(200)
            await pg.click('#bf-modal [data-mtbd]'); await pg.click('#bf-modal [data-mact="create"]'); await pg.wait_for_timeout(1500)
            st = await pg.evaluate("({n:window.__DB.briefings.length, edit:!!document.querySelector('#bfm .bfm-title'), tbd:document.getElementById('bfm').textContent.indexOf('Date à définir')>-1})")
            print('  ', st)
            R.check('J. briefing cree, ouvert directement, date a definir', st['n']==2 and st['edit'] and st['tbd'])
            await pg.click('#bfm [data-m="fixdate"]'); await pg.wait_for_timeout(500)
            st = await pg.evaluate("({d:(document.querySelector('#bfm [data-m=date]')||{}).value, shoots:JSON.parse(localStorage.getItem('6flt_clients'))[0].shoots.map(function(x){return x.date})})")
            print('  ', st)
            R.check('K. fixer une date : inscrite au planning du client', st['d'] and st['d'] in st['shoots'])
            # pas de debordement horizontal
            ov = await pg.evaluate("(function(){ var W=document.documentElement.clientWidth, n=0; document.querySelectorAll('#bfm *').forEach(function(el){ var r=el.getBoundingClientRect(); if(r.width && r.right>W+1) n++; }); return n; })()")
            R.check('L. aucun debordement a 390 px', ov==0)
            R.check('M. aucune erreur JS', not errs); print('  ', errs[:3])
            await ctx.close()
            # ordinateur : l'ecran mobile reste cache, l'editeur normal s'affiche
            ctx = await br.new_context(viewport={'width':1366,'height':768}, service_workers='block', locale='fr-FR')
            await ctx.route('**/*', R.route); await ctx.add_init_script(R.seed(date='2026-10-15'))
            pg = await ctx.new_page(); e2=[]; pg.on('pageerror', lambda e: e2.append(str(e)))
            await pg.goto(R.BASE+'index.html'); await pg.wait_for_timeout(2500); await pg.evaluate("switchView('planning')"); await pg.wait_for_timeout(600)
            R.check('N. ordinateur : editeur normal, ecran mobile cache', await pg.evaluate("getComputedStyle(document.getElementById('bfm')).display=='none' && getComputedStyle(document.querySelector('.bf-wrap')).display!='none'") and not e2)
            await br.close()
    finally: srv.terminate()
    print('ECHECS', R.fails)
asyncio.run(main())
